development:
  adapter: mysql2
  encoding: utf8
#  reconnect: false
  database: slackboard_development
  pool: 5
  username: root
  password:
  host: localhost

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: slackboard_production
  pool: 5
  username: root
  password:
  host: localhost
